#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/lenovo/akita_row_wifi

BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

BUILD_BROKEN_DUP_RULES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := akita_row_wifi
TARGET_NO_BOOTLOADER := true

####### TEST
# Debug
TARGET_USES_LOGD := true

# AVB
# BOARD_AVB_ENABLE := true
BOARD_USES_RECOVERY_AS_BOOT := false #????
# BOARD_AVB_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)

# DTBO
# BOARD_KERNEL_SEPARATED_DTBO := true

TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz-dtb
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)/prebuilt/dtb
BOARD_USES_METADATA_PARTITION := true
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
####### TEST

# Boot Image
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_TAGS_OFFSET := 0x07808000
BOARD_RAMDISK_OFFSET := 0x11a88000
BOARD_DTB_OFFSET := 0x07808000 # ???
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive
# BOARD_KERNEL_CMDLINE += androidboot.hardware=mt6761
# BOARD_KERNEL_CMDLINE += androidboot.boot_devices=bootdevice

BOARD_BUILD_SYSTEM_ROOT_IMAGE := false

# BOARD_MKBOOTIMG_ARGS := --base $(BOARD_KERNEL_BASE) # missibg from twrp
# BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET) # missibg from twrp
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
# BOARD_MKBOOTIMG_ARGS += --second_offset 0x00e88000
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET) # missibg from twrp
# BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE) # missibg from twrp
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)

# Display
TARGET_SCREEN_DENSITY := 240

BOARD_SEPOLICY_DIRS := device/lineage/sepolicy/mediatek/vendor/

# HIDL
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml

# Board
TARGET_BOARD_INFO_FILE := $(DEVICE_PATH)/board-info.txt

# Kernel
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_SOURCE := kernel/lenovo/akita_row_wifi
TARGET_KERNEL_CONFIG := akita_row_wifi_defconfig
TARGET_KERNEL_NO_GCC := true
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb

# Partitions
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
#Boot
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
#Recovery
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
#System
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 4085252096
# BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
#Vendor
BOARD_VENDORIMAGE_PARTITION_SIZE := 838860800
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
#Cache
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
#User data
BOARD_USERDATAIMAGE_PARTITION_SIZE := 25192021504
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true

# MTK Hardware
BOARD_HAS_MTK_HARDWARE  := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE            := true

# Platform
TARGET_BOARD_PLATFORM := mt6761

# Recovery
TARGET_RECOVERY_FSTAB        := $(DEVICE_PATH)/rootdir/etc/fstab.mt6761
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"

# XML Audio
USE_XML_AUDIO_POLICY_CONF := 1

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

TARGET_SCREEN_WIDTH  := 800
TARGET_SCREEN_HEIGHT := 1280

# Security patch level
# VENDOR_SECURITY_PATCH := 2019-08-05
# PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2021-08
PLATFORM_SECURITY_PATCH := 2021-08

# HIDL
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/manifest.xml
DEVICE_MATRIX_FILE := $(DEVICE_PATH)/compatibility_matrix.xml
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE := $(DEVICE_PATH)/framework_compatibility_matrix.xml

-include vendor/lenovo/akita_row_wifi/BoardConfigVendor.mk
